# Generated by Django 4.0.4 on 2022-04-21 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busTicketBooking', '0019_alter_bus_manufacturer_alter_bus_operator_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='mobile',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
