# Generated by Django 4.0.4 on 2022-04-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busTicketBooking', '0020_remove_passenger_mobile_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='Class',
            field=models.CharField(choices=[('ECONOMY', 'Economy Class')], default='ECONOMY', max_length=10),
        ),
        migrations.AlterField(
            model_name='bus',
            name='manufacturer',
            field=models.CharField(choices=[('WRIGHTBUS', 'Wrightbus')], default='HINO', max_length=50),
        ),
        migrations.AlterField(
            model_name='bus',
            name='operator_name',
            field=models.CharField(choices=[('IRL Citylink', 'IRL Citylink')], default='...', max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(choices=[('GALWAY', 'galway'), ('DUBLIN', 'Dublin')], default='...', max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_station',
            field=models.CharField(choices=[('DUBLIN', 'Dublin'), ('GALWAY', 'Galway')], default='...', max_length=50),
        ),
    ]
